In [1]:
import pandas as pd
import numpy as np

In [2]:
dfx = pd.read_csv("Diabetes_XTrain.csv")

In [3]:
dfy = pd.read_csv("Diabetes_YTrain.csv")

In [4]:
X = dfx.values
Y = dfy.values

In [5]:
Y = Y.reshape((-1,))
print(Y.shape)


(576,)


In [6]:
def dist(x1,x2):
    return np.sqrt((sum(x1-x2))**2)

In [7]:
def knn(X,Y,querypoint,k=5):
    vals=[]
    m = X.shape[0]
    for i in range(m):
        d=dist(querypoint,X[i])
        vals.append((d,Y[i]))
    vals = sorted(vals)
    vals = vals[:k]
    vals = np.array(vals)
    new_vals = np.unique(vals[:1],return_counts=True)
    print(new_vals)
    idx = new_vals[1].argmax()
    pred = new_vals[0][idx]
    return pred

In [8]:
x_test= pd.read_csv("Diabetes_XTest.csv")

In [9]:
x_test = x_test.values
print(x_test[0])

[  0.    180.     90.     26.     90.     36.5     0.314  35.   ]


In [17]:
m = x_test.shape[0]
ans = []
for i in range(m):
    k = knn(X,Y,x_test[i],150)
    if (k<0.5):
        k = 0
    else:
        k=1
    ans.append(k)
ans = np.array(ans)
print(ans)


(array([0.574, 1.   ]), array([1, 1], dtype=int64))
(array([0.   , 0.269]), array([1, 1], dtype=int64))
(array([0.   , 0.012]), array([1, 1], dtype=int64))
(array([0.   , 0.437]), array([1, 1], dtype=int64))
(array([0.   , 0.067]), array([1, 1], dtype=int64))
(array([0.   , 0.478]), array([1, 1], dtype=int64))
(array([1.   , 2.329]), array([1, 1], dtype=int64))
(array([1.   , 1.197]), array([1, 1], dtype=int64))
(array([0.   , 0.338]), array([1, 1], dtype=int64))
(array([0.  , 0.13]), array([1, 1], dtype=int64))
(array([0.   , 0.183]), array([1, 1], dtype=int64))
(array([0.   , 0.381]), array([1, 1], dtype=int64))
(array([ 1.   , 13.807]), array([1, 1], dtype=int64))
(array([0.   , 0.829]), array([1, 1], dtype=int64))
(array([0.   , 0.017]), array([1, 1], dtype=int64))
(array([0.16, 1.  ]), array([1, 1], dtype=int64))
(array([0.   , 0.151]), array([1, 1], dtype=int64))
(array([0.   , 0.214]), array([1, 1], dtype=int64))
(array([0.467, 1.   ]), array([1, 1], dtype=int64))
(array([1.   ,

(array([0.   , 0.474]), array([1, 1], dtype=int64))
(array([0.   , 0.159]), array([1, 1], dtype=int64))
(array([0.579, 1.   ]), array([1, 1], dtype=int64))
(array([0.092, 1.   ]), array([1, 1], dtype=int64))
(array([1.   , 1.037]), array([1, 1], dtype=int64))
(array([1.   , 1.425]), array([1, 1], dtype=int64))
(array([0.421, 1.   ]), array([1, 1], dtype=int64))
(array([0.   , 0.536]), array([1, 1], dtype=int64))
(array([0.   , 0.039]), array([1, 1], dtype=int64))
(array([0.   , 0.492]), array([1, 1], dtype=int64))
(array([0.008, 1.   ]), array([1, 1], dtype=int64))
(array([0.   , 0.022]), array([1, 1], dtype=int64))
(array([0.007, 1.   ]), array([1, 1], dtype=int64))
(array([0.   , 0.082]), array([1, 1], dtype=int64))
(array([0.   , 0.098]), array([1, 1], dtype=int64))
(array([0.   , 0.052]), array([1, 1], dtype=int64))
(array([0.   , 0.186]), array([1, 1], dtype=int64))
[1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 1 0 0 0 

In [18]:
answer = {"Outcome": ans}
df = pd.DataFrame(answer)
df.to_csv("answer5.csv",index=False)